displayName=Inferno/Colo Tracker
author=evaan
support=https://github.com/evaan/infernotracker
description=A plugin to help track your inferno and colo attempts.
tags=inferno, colo, tracker
plugins=xyz.evaan.InfernoTrackerPlugin